const ACTIONS = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    SIGNIN_REQUEST: "SIGNIN_REQUEST",
    SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
    SIGNIN_FAILURE: "SIGNIN_FAILURE",
    UPDATE_USER: "UPDATE_USER",
    UPDATE_API_DATA: "UPDATE_API_DATA",

    CHANGING_PASS: "CHANGING_PASS",
    PASS_CHANGED: "PASS_CHANGED",
    CHANGING_PASS_ERR:"CHANGING_PASS_ERR",

    CHANGING_EMAIL: "CHANGING_EMAIL",
    EMAIL_CHANGED: "EMAIL_CHANGED",
    CHANGING_EMAIL_ERR:"CHANGING_EMAIL_ERR",

    EMAIL_CHANGED: "EMAIL_CHANGED",
    CHANGE_API: "CHANGE_API",
  };
  
  export default ACTIONS;